/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_visionvera_bmob_jni_HelloJni */

#ifndef _Included_com_visionvera_bmob_jni_HelloJni
#define _Included_com_visionvera_bmob_jni_HelloJni
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_visionvera_bmob_jni_HelloJni
 * Method:    add
 * Signature: (II)I
 */
JNIEXPORT jint
JNICALL Java_com_visionvera_bmob_jni_HelloJni_add
        (JNIEnv * , jobject, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
